export const homeObjectOne = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Начать',
    description: 'Мы помогаем владельцам бизнеса повысить свою прибыль. Наша команда уникальных специалистов поможет Вам достигнуть цели!',
    headline: 'Специалисты по лидогенерации для бизнесов в онлайне',
    lightText: true,
    topLine: 'Маркетинговое Агентство',
    img: require('../../images/svg-1.svg').default,
    alt: 'Image',
    start: '',
}
export const homeObjectTwo = {
    lightBg: true,
    primary: false,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Начать',
    description: 'Мы помогаем владельцам бизнеса повысить свою прибыль. Наша команда уникальных специалистов поможет Вам достигнуть цели!',
    headline: 'Специалисты по лидогенерации для бизнесов в онлайне',
    lightText: false,
    topLine: 'Маркетинговое Агентство',
    img: require('../../images/svg-2.svg').default,
    alt: 'Image',
    start: 'true',
}
export const homeObjectThree = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Начать',
    description: 'Мы помогаем владельцам бизнеса повысить свою прибыль. Наша команда уникальных специалистов поможет Вам достигнуть цели!',
    headline: 'Специалисты по лидогенерации для бизнесов в онлайне',
    lightText: true,
    topLine: 'Маркетинговое Агентство',
    img: require('../../images/svg-3.svg').default,
    alt: 'Image',
    start: '',
}
export const homeObjectFour = {
    lightBg: true,
    primary: false,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Начать',
    description: 'Мы помогаем владельцам бизнеса повысить свою прибыль. Наша команда уникальных специалистов поможет Вам достигнуть цели!',
    headline: 'Специалисты по лидогенерации для бизнесов в онлайне',
    lightText: false,
    topLine: 'Маркетинговое Агентство',
    img: require('../../images/profile.svg').default,
    alt: 'Image',
    start: 'true',
}